# Generated by Django 4.0.4 on 2022-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_org', models.CharField(default='', max_length=30, verbose_name='организация клиента')),
                ('bill_number', models.IntegerField(default=1, verbose_name='номер счета')),
                ('bill_sum', models.IntegerField(default=1, verbose_name='сумма по счету')),
                ('bill_date', models.DateField(verbose_name='дата счета')),
            ],
        ),
    ]
