# Generated by Django 4.0.4 on 2022-05-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('bills', '0002_alter_bill_bill_number_alter_bill_client_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.organization', unique=True, verbose_name='организация клиента'),
        ),
    ]
