# Generated by Django 4.0.4 on 2022-05-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('bills', '0003_alter_bill_client_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.IntegerField(default=1, verbose_name='номер счета'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.organization', verbose_name='организация клиента'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('client_org', 'bill_number')},
        ),
    ]
