# Generated by Django 4.0.4 on 2022-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='клиент'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('client', 'organization_name')},
        ),
    ]
